name: C/C++ CI

on:
  push:
    branches:
      - master
      - '*smoketest*'

  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: ./configure
    - name: debug make
      run: make BUILD=debug
    - name: debug make check
      run: make BUILD=debug check
    - name: release make
      run: make BUILD=release
    - name: release make check
      run: make BUILD=release check
